### ISSUE TITLE
[Bug] setuptools 应该是被限制在一个范围，已经无法使用最新的版本

### ISSUE THREAD

**Issue by xueying4402** [AimRT/AimRT#16]
**Version of AimRT**
`7d5fe683196bd723d0cafff1abffa8f5c9a81bd1`

**Environments**
其他环境使用了满足要求的版本

**Describe the bug**
当使用`setuptools`工具的最新版本75.1.0时，将会构建失败，应该修改文档相关[描述](https://github.com/AimRT/AimRT/blob/7d5fe683196bd723d0cafff1abffa8f5c9a81bd1/document/sphinx-cn/tutorials/quick_start/installation_py.md?plain=1#L54)。

**Expected behavior**
成功构建

**Actual behavior**
```Traceback (most recent call last):
  File "/root/aimRT/aimRT/build/src/protocols/plugins/ros2_plugin_proto/ament_cmake_python/ros2_plugin_proto/setup.py", line 4, in <module>
    setup(
  File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 311, in run
    self.find_sources()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 319, in find_sources
    mm.run()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 545, in run
    self.prune_file_list()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/sdist.py", line 161, in prune_file_list
    super().prune_file_list()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/sdist.py", line 380, in prune_file_list
    base_dir = self.distribution.get_fullname()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_core_metadata.py", line 267, in get_fullname
    return _distribution_fullname(self.get_name(), self.get_version())
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
    canonicalize_version(version, strip_trailing_zero=False),
TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
```

**Additional context**
当使用61.0的时候可以成功构建

**Comment by AimRT** [comment]
我尝试使用 setuptools=75.1.0 复现该问题失败了，经过一些搜索，这可能与你本地的 packaging 包的版本有关，详见 https://github.com/pypa/setuptools/issues/4501 。

简单来说，setuptools 并不依赖 packaging 包，但是当您本地安装有 packaging 包时，setuptools 会使用它并且有一个最低适配版本的要求，但由于 setuptools 并不将其作为依赖项，所以自然也就没有指定 packaging 包的最低适配版本，所以造成了一些冲突。

解决方案：
1. 升级或者卸载本地的 packaging 包。
2. 降级 setuptools 版本与本地的 packaging 包的版本适配。

考虑到这应该是 setuptools 的 bug，高于 61.0 版本的 setuptools 在无上述冲突的情况下均可用，且限制 setuptools 的版本并不能完全解决该问题，用户的 packaging 包总是会有各种可能性与 setuptools 的版本不适配。所以文档中不会限制 setuptools 的版本，未来的文档中可能会做出一些额外说明。
